* ProceedHub Backend

** Descripción

Este proyecto es el backend de ProceedHub que sera para la aplicación web HAMUK, esta desarrollada con Spring Boot y Gradle. Proporciona servicios RESTful para la gestión de usuarios y la seguridad de la aplicación.

** Requisitos

- Java 21 o superior
- Gradle 7.5 o superior

** Configuración del Proyecto

*** Clonar el Repositorio

#+begin_src sh
git clone https://github.com/tu-usuario/proceedhub-backend.git
cd proceedhub-backend
#+end_src

*** Construir el Proyecto

#+begin_src sh
./gradlew build
#+end_src

*** Ejecutar la Aplicación

#+begin_src sh
./gradlew bootRun
#+end_src

** Endpoints

*** Crear Usuario

- URL: /users
- Método: POST
- Cuerpo de la Solicitud:

#+begin_src json
{
  "username": "nombre_usuario",
  "email": "correo@ejemplo.com",
  "password": "contraseña",
  "roles": ["ROLE_USER"]
}
#+end_src

- Respuesta Exitosa:

#+begin_src json
{
  "message": "User created successfully"
}
#+end_src

*** Obtener Todos los Usuarios

- URL: /users
- Método: GET
- Respuesta Exitosa:

#+begin_src json
{
  "message": "Aqui todos los ususarios papu"
}
#+end_src

** Seguridad

La configuración de seguridad se encuentra en el archivo ~SecurityConfig.java~. Actualmente, permite el acceso público al endpoint /users y requiere autenticación para cualquier otro endpoint.

** Contribuir

1. Haz un fork del proyecto.
2. Crea una nueva rama (~git checkout -b feature/nueva-funcionalidad~).
3. Realiza tus cambios y haz commit (~git commit -am 'Añadir nueva funcionalidad'~).
4. Sube tus cambios a la rama (~git push origin feature/nueva-funcionalidad~).
5. Abre un Pull Request.

** Licencia

Este proyecto está licenciado bajo la Licencia MIT. Consulta el archivo ~LICENSE~ para más detalles.